# Generated by Django 5.0.4 on 2024-05-09 11:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorted', models.BooleanField(default=False, verbose_name='Сортировка')),
                ('made', models.IntegerField(default=0, verbose_name='Сделано')),
                ('parity', models.IntegerField(default=0, verbose_name='Важно')),
                ('chose', models.IntegerField(default=0, verbose_name='Избрано')),
                ('selection', models.IntegerField(default=0, verbose_name='Отбор')),
                ('selection_date', models.DateField(default=datetime.date.today, verbose_name='Отбор по сроку')),
                ('selection_key', models.CharField(max_length=150, verbose_name='Отбор по ключу')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-user'],
            },
        ),
    ]
