# Generated by Django 5.0.4 on 2024-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='selection_date',
            field=models.DateField(null=True, verbose_name='Отбор по сроку'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='selection_key',
            field=models.CharField(max_length=150, null=True, verbose_name='Отбор по ключу'),
        ),
    ]
