# Generated by Django 5.0.4 on 2024-05-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_alter_userinfo_selection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='chose',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Избрано'), (2, 'Неизбрано')], default=0, verbose_name='Избрано'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='made',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Невыполнено'), (2, 'Выполнено')], default=0, verbose_name='Сделано'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='parity',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Срочно'), (2, 'Несрочно')], default=0, verbose_name='Срочно'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='selection',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Текст'), (2, 'Дата')], default=0, verbose_name='Отбор'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sorted',
            field=models.BooleanField(choices=[(0, 'Срок, срочность'), (1, 'Срочность, срок')], default=False, verbose_name='Сортировка'),
        ),
    ]
