# Generated by Django 5.0.4 on 2024-05-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_userinfo_chose_alter_userinfo_made_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='selection_date',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='chose',
            field=models.BooleanField(default=0, verbose_name='Избрано'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='made',
            field=models.BooleanField(default=0, verbose_name='Сделано'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='parity',
            field=models.BooleanField(default=0, verbose_name='Срочно'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='selection',
            field=models.BooleanField(default=0, verbose_name='Отбор'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sorted',
            field=models.BooleanField(default=False, verbose_name='Сортировка'),
        ),
    ]
